#!/usr/bin/env sh

# This script is used to deploy a lambda by zipping up a folder
# Args:
# 1. ARN of Lambda

python3 -m pip install -t package -r requirements.txt
zip -FSr lambda.zip package
zip -urj lambda.zip src/*
aws lambda update-function-code --function-name $1 --zip-file fileb://lambda.zip
